#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:
  httpbin:
    image: kennethreitz/httpbin:latest
    restart: always
    ports:
      - "80:80"
    networks:
      apisix:

#  kt-web-0:
#    image: kt-web:v0
#    restart: always
#    depends_on:
#      - nacos-standalone-derby
#    ports:
#      - "22222:22222"
#    networks:
#      apisix:
#
#  kt-web-nacos-service-22225:
#    image: kt-web-nacos-service-22225:v2
#    restart: always
#    depends_on:
#      - nacos-standalone-derby
#    ports:
#      - "22225:22225"
#    networks:
#      apisix:
#
#  kt-web-nacos-service-22226:
#    image: kt-web-nacos-service-22226:v1
#    restart: always
#    depends_on:
#      - nacos-standalone-derby
#    ports:
#      - "22226:22226"
#    networks:
#      apisix:

  kt-web-nacos-service-22226:
    image: kt-web-nacos-service-22226:v2
    restart: always
    depends_on:
      - nacos-standalone-derby
    ports:
      - "22226:22226"
    networks:
      apisix:

  nacos-standalone-derby-new:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-derby-new
    restart: always
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: "false"
      NACOS_AUTH_TOKEN: "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh"
      NACOS_AUTH_IDENTITY_KEY: "nacos_key"
      NACOS_AUTH_IDENTITY_VALUE: "nacos_value"
      JVM_XMS: 512m
      JVM_XMX: 512m
    ports:
      - "8080:8080/tcp"
      - "8848:8848/tcp"
      - "9848:9848/tcp"
    networks:
      apisix:

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.14.1-debian}
#    image: apache/apisix:3.14.1-alpine-with-java-plugin
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/tmp:/tmp:rw
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
      - "8088:8088/tcp"
    networks:
      apisix:

  etcd:
    image: bitnamilegacy/etcd:3.5.11
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      apisix:

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
